spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/hospital
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
hibernate:
  dialect: org.hibernate.dialect.PostgresPlusDialect