CREATE TABLE medicos(
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
telefono VARCHAR(10) NOT NULL UNIQUE,
edad SMALLINT NOT NULL,
genero VARCHAR(20) NOT NULL,
especialidad VARCHAR(30) NOT NULL,
ciudad VARCHAR(40) NOT NULL,
calle SMALLINT NOT NULL,
carrera SMALLINT NOT NULL,
complemento SMALLINT,
letra_complemento CHAR(1)
);